[Issue #96] Implemented a Summary Page post Quiz submission
yagnik2411/Quiz-Genius pull request #99
Opened 2024-10-15 18:46 UTC by rishichirchi

This PR implements a summary page that displays the results of the quiz after submission, addressing issue #<insert_issue_number>.

### Summary of Changes:
- Created a new `SummaryPage` that shows the number of correct answers out of the total questions.
- Displayed the percentage of correct answers.
- Listed each question along with its correctness (correct/incorrect).

![Screenshot_20241015-235015_quiz_genius](https://github.com/user-attachments/assets/25e821b2-09e4-4de6-9ade-b9853fd6f094)

### Related Issues:
Fixes #96 .

2024-10-15 19:00 UTC, KirolosMFahem requested changes
The failure in the GitHub Actions job is due to an error in the `pubspec.lock` file. The specific error message is:

```
Failed parsing lock file:
Error on line 146, column 1 of pubspec.lock: Expected ':'.
    ╷
146 │ <<<<<<< HEAD
    │ ^
    ╵
Consider deleting the file and running `flutter pub get` to recreate it.
```

### Recommended Fix:
1. Delete the `pubspec.lock` file.
2. Run `flutter pub get` to recreate the `pubspec.lock` file.

This error is likely due to a merge conflict marker left in the `pubspec.lock` file. Removing and regenerating the file should resolve the issue.

2024-10-15 20:15 UTC, rishichirchi commented
@KirolosMFahem I have made the changes, can you check once?

2024-10-16 13:58 UTC, KirolosMFahem approved these changes

2024-10-16 14:00 UTC, KirolosMFahem commented
### Summary of Pull Request #99: [Issue #96] Implemented a Summary Page post Quiz submission

This PR implements a summary page that displays the results of the quiz after submission, addressing issue #96.

#### Summary of Changes:
- Created a new `SummaryPage` that shows the number of correct answers out of the total questions.
- Displays the percentage of correct answers.
- Lists each question along with its correctness (correct/incorrect).
- Updated various files to integrate the `SummaryPage` into the application flow.

#### Related Files:
- `android/gradle/wrapper/gradle-wrapper.properties`
- `lib/main.dart`
- `lib/pages/home_page.dart`
- `lib/pages/quiz_page.dart`
- `lib/pages/summary_page.dart` (new file)
- `lib/utils/my_route.dart`
- `lib/utils/profile_image_service.dart`

#### Related Issues:
- Fixes [Issue #96](https://github.com/yagnik2411/Quiz-Genius/issues/96)

2024-10-16 14:26 UTC, rishichirchi commented
@KirolosMFahem can you merge this PR please?

2024-10-16 14:31 UTC, KirolosMFahem commented
> @KirolosMFahem can you merge this PR please?

@yagnik2411

2024-10-17 03:06 UTC, yagnik2411 commented
but we already have previous quiz page for this

2024-10-17 03:07 UTC, yagnik2411 commented
@KirolosMFahem whats point of this to include in app instead of you can update previous quiz page.

2024-10-17 04:07 UTC, rishichirchi commented
@yagnik2411 the point of this PR is to improve the user experience of user. The current previous quiz page that can be accessed from home page has summary of all the previous quizzes but it doesn't show the analysis of the most recent one. The PR implements a feature where the user can see what questions he did right and wrong and a summary of correct questions right before moving to home screen. Then it can also be viewed by previous quiz button.

2024-10-17 04:17 UTC, rishichirchi commented
https://github.com/user-attachments/assets/ea3a55a8-c0ab-411a-87b9-47aa4481baf3

2024-10-17 18:28 UTC, KirolosMFahem commented
from here @yagnik2411 is the one with the final decision

2024-10-18 10:02 UTC, yagnik2411 commented
> @yagnik2411 the point of this PR is to improve the user experience of user. The current previous quiz page that can be accessed from home page has summary of all the previous quizzes but it doesn't show the analysis of the most recent one. The PR implements a feature where the user can see what questions he did right and wrong and a summary of correct questions right before moving to home screen. Then it can also be viewed by previous quiz button.

i got the point. good work on thinking of UI.

2024-10-18 10:03 UTC, yagnik2411 commented
I will test and merge asap

2024-10-18 10:04 UTC, yagnik2411 commented
@rishichirchi did you add all summary pages to all types of quizzes?

2024-10-18 10:10 UTC, rishichirchi commented
It's done for true or false type for now

2024-10-18 15:47 UTC, yagnik2411 commented
you need to do for mcq quiz

2024-10-18 16:37 UTC, rishichirchi commented
Surely will work on it. I didn't pull the code before doing this pr so didn't add for MCQ! It would help if you could merge it!

2024-10-20 07:21 UTC, yagnik2411 commented
@rishichirchi okay
but first make issues and mention here.

2024-10-22 02:52 UTC, rishichirchi commented
@yagnik2411 I have created the required issue ie issue #123 , which I will be working on next. Hope this PR gets merged now!

2024-10-24 13:24 UTC, yagnik2411 commented
lib/pages/home_page.dart
lib/pages/quiz_page.dart
  @rishichirchi we have issues

2024-10-24 13:28 UTC, rishichirchi commented
@yagnik2411 will check them out

2024-10-24 14:04 UTC, KirolosMFahem commented
please do `sync fork` to solve the conflicts

2024-11-07 22:20 UTC, KirolosMFahem commented
@rishichirchi please resolve the Conflicting files ASAP for final test
once done DM me and @yagnik2411 in the comments

2024-11-08 03:13 UTC, rishichirchi commented
Yes, will do it today

2024-11-08 13:04 UTC, KirolosMFahem commented
Conflicting files
lib/main.dart
lib/pages/home_page.dart
lib/pages/quiz_page.dart

2026-05-01 09:08 UTC, closed without merging